### ISSUE TITLE
The Day is displayed incorrectly

### ISSUE THREAD

**Issue by genesisfan** [thotmx/mod_efemerides#1]
Hi @thotmx 
When I use 'Formatted Date = No' the day is displayed correctly. But when I use 'Formatted Date = Yes' and use "j F, Y", "d M, Y" or "d/m/Y" it's displaying 30 instead of 31.

**Comment by thotmx** [comment]
What's your timezone?

**Comment by genesisfan** [comment]
My timezone is CET.

**Comment by thotmx** [comment]
Please, could you give the date that you are testing?

**Comment by thotmx** [comment]
On master, I've removed the timezone offset. Could you test it?

**Comment by genesisfan** [comment]
I've tested it with the new master module and it works now. Even with "Formatted Date" No and Yes. The day is displayed correctly. Thank you so much @thotmx!!

**Comment by thotmx** [comment]
@genesisfan thanks for reporting this. I'm going to close this issue.
